name: Renovate Config

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@da43ac6581a6fd2ae27d5f2cb8b6023b8596fd77 # main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@da43ac6581a6fd2ae27d5f2cb8b6023b8596fd77 # main
