name: Renovate Config

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@2d1ea0dc63268d7119570a2adfd80abfa8fa304e # main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@2d1ea0dc63268d7119570a2adfd80abfa8fa304e # main
